apiVersion: serving.knative.dev/v1alpha1
kind: Service
metadata:
  name: pdf
spec:
  runLatest:
    configuration:
      revisionTemplate:
        spec:
          container:
            image: gcr.io/vpc-demo-225319/pdf-service